import { FETCH_CAT_SUCCESS, FETCH_CAT_REQUEST, FETCH_CAT_ERROR, fetchCat } from './cat';
import { FETCH_DOG_SUCCESS, FETCH_DOG_REQUEST, FETCH_DOG_ERROR, fetchDog } from './dog';

export { FETCH_CAT_SUCCESS, FETCH_CAT_REQUEST, FETCH_CAT_ERROR, 
  FETCH_DOG_SUCCESS, FETCH_DOG_REQUEST, FETCH_DOG_ERROR, fetchCat, fetchDog };