import { FETCH_CAT_SUCCESS, FETCH_CAT_REQUEST, FETCH_CAT_ERROR, fetchCat, DELETE_CAT_ERROR, DELETE_CAT_SUCCESS, DELETE_CAT_REQUEST, deleteCat } from './cat';
import { FETCH_DOG_SUCCESS, FETCH_DOG_REQUEST, FETCH_DOG_ERROR, fetchDog, DELETE_DOG_ERROR, DELETE_DOG_REQUEST, DELETE_DOG_SUCCESS, deleteDog } from './dog';

export { FETCH_CAT_SUCCESS, FETCH_CAT_REQUEST, FETCH_CAT_ERROR,
  FETCH_DOG_SUCCESS, FETCH_DOG_REQUEST, FETCH_DOG_ERROR, fetchCat, fetchDog, DELETE_CAT_ERROR, DELETE_CAT_SUCCESS, DELETE_CAT_REQUEST, deleteCat, DELETE_DOG_ERROR, DELETE_DOG_REQUEST, DELETE_DOG_SUCCESS, deleteDog };